services:
  ctfapp:
    build: .
    restart: unless-stopped

  nginx:
    image: nginx:1.22.0
    ports:
      - "54321:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ctfapp
